version: "3.8"

services:
  api:
    build:
      context: ./docker/back
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - app-network

  front:
    build:
      context: ./docker/front
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
