version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace/backend
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5000:5000"
    networks:
      - app-network

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace/frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
