# .github/workflows/auto-approve.yml
name: Auto Approve

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    steps:
      - name: 自動Approve
        uses: hmarr/auto-approve-action@v3
        with:
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
